name: masked_text_formatter
description: Masked text input for flutter.
version: 0.0.1
author: dkzwm<aidkzwm@gmail.com>
homepage: https://github.com/dkzwm/masked_text_formatter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

